name: Build TTF from Glyphs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install fontmake

      - name: Build TTF from Glyphs
        run: |
          mkdir -p fonts
          fontmake -g sources/SimplexSans-Regular.glyphs -o ttf --output-dir fonts
      
      - name: Upload TTF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: simplex-ttf
          path: fonts/*.ttf
